<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01167pam a2200301 a 4500</leader>
<controlfield tag='001'>a8548497</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100126s2011    maua     b    000 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010001768</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0137057199 (pbk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780137057191 (pbk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>NNfCLS</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>LB1632</subfield>
<subfield code='b'>.A13 2011</subfield>
</datafield>
<datafield tag='245' ind1='0' ind2='0'>
<subfield code='a'>50 instructional routines to develop content literacy /</subfield>
<subfield code='c'>Douglas Fisher ... [et al.].</subfield>
</datafield>
<datafield tag='246' ind1='3' ind2=' '>
<subfield code='a'>Fifty instructional routines to develop content literacy</subfield>
</datafield>
<datafield tag='250' ind1=' ' ind2=' '>
<subfield code='a'>2nd ed.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>Boston :</subfield>
<subfield code='b'>Pearson,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>ix, 153 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>28 cm.</subfield>
</datafield>
<datafield tag='500' ind1=' ' ind2=' '>
<subfield code='a'>First edition published as Fifty content area strategies for adolescent literacy.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Reading (Secondary)</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Content area reading.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>Fisher, Douglas,</subfield>
<subfield code='d'>1965-</subfield>
</datafield>
<datafield tag='730' ind1='0' ind2=' '>
<subfield code='a'>Fifty content area strategies for adolescent literacy.</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)475458177</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)631281535</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LB1632 .A13 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215353330</subfield>
<subfield code='d'>6/9/2010</subfield>
<subfield code='e'>5/27/2010</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='n'>1</subfield>
<subfield code='p'>$22.99</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>5/13/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01183cam a2200301 a 4500</leader>
<controlfield tag='001'>a8707413</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100208s2011    nyua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010004687</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780415871808 (paper : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0415871808 (paper : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780415871792 (cloth : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0415871794 (cloth : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780203846438 (ebook.</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0203846435 (ebook.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>BTCTA</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>P115.2</subfield>
<subfield code='b'>.K33 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Kabuto, Bobbie.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Becoming biliterate :</subfield>
<subfield code='b'>identity, ideology, and learning to read and write in two languages /</subfield>
<subfield code='c'>Bobbie Kabuto.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>New York :</subfield>
<subfield code='b'>Routledge,</subfield>
<subfield code='c'>2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xviii, 139 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>23 cm.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 128-132) and index.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Bilingualism in children.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Second language acquisition.</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)368025527</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)669269514</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>P115.2 .K33 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215376471</subfield>
<subfield code='d'>10/21/2010</subfield>
<subfield code='e'>10/21/2010</subfield>
<subfield code='k'>NEWBOOKS</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='n'>1</subfield>
<subfield code='p'>$41.95</subfield>
<subfield code='r'>M</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>9/29/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01199pam a2200301 a 4500</leader>
<controlfield tag='001'>a8519432</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>091125s2011    nyua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2009049162</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780073378794 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0073378798 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='043' ind1=' ' ind2=' '>
<subfield code='a'>n-us---</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>LB1623.5</subfield>
<subfield code='b'>.R84 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Rubinstein, Gary.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Beyond survival :</subfield>
<subfield code='b'>how to thrive in middle and high school for beginning and improving teachers /</subfield>
<subfield code='c'>Gary Rubinstein.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>New York :</subfield>
<subfield code='b'>McGraw-Hill,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xiii, 161 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>24 cm.</subfield>
</datafield>
<datafield tag='490' ind1='1' ind2=' '>
<subfield code='a'>The practical guide series</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 155-157) and index.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Middle school teaching</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>High school teaching</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>First year teachers</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='830' ind1=' ' ind2='0'>
<subfield code='a'>Practical guide series (McGraw-Hill Companies)</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)471452273</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)607073230</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LB1623.5 .R84 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215324141</subfield>
<subfield code='d'>4/29/2010</subfield>
<subfield code='e'>4/15/2010</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='n'>1</subfield>
<subfield code='p'>$36.25</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>4/7/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>00874cam a2200229 a 4500</leader>
<controlfield tag='001'>a8513900</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>090807s2011    mauc          000 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2009032862</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780135094044 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0135094046 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>YDX</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>LB2806</subfield>
<subfield code='b'>.M434 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Midlock, Stephen F.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Case studies for educational leadership :</subfield>
<subfield code='b'>solving administrative dilemmas /</subfield>
<subfield code='c'>Stephen F. Midlock.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>Boston :</subfield>
<subfield code='b'>Pearson,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xi, 174 p. :</subfield>
<subfield code='b'>port. ;</subfield>
<subfield code='c'>24 cm.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Educational leadership</subfield>
<subfield code='v'>Case studies.</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)429816955</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)575066822</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LB2806 .M434 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215312252</subfield>
<subfield code='d'>4/8/2010</subfield>
<subfield code='e'>3/30/2010</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='n'>1</subfield>
<subfield code='p'>$73.33</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>3/16/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01792cam a2200325 a 4500</leader>
<controlfield tag='001'>a8694933</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100423s2011    nyua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010017581</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780415873796 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0415873797 (pbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780415873789 (hbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0415873789 (hbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780203844847 (ebk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>020384484X (ebk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>BTCTA</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='043' ind1=' ' ind2=' '>
<subfield code='a'>n-us---</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>E175.8</subfield>
<subfield code='b'>.V35 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>VanSledright, Bruce.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='4'>
<subfield code='a'>The challenge of rethinking history education :</subfield>
<subfield code='b'>on practices, theories, and policy /</subfield>
<subfield code='c'>Bruce A. VanSledright.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>New York :</subfield>
<subfield code='b'>Routledge,</subfield>
<subfield code='c'>2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>224 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>23 cm.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. [195]-197) and index.</subfield>
</datafield>
<datafield tag='505' ind1='0' ind2=' '>
<subfield code='a'>Seeking a more potent approach to teaching history -- On the limits of collective memorialization and persistent instruction -- The case of Thomas Becker : using knowledge of history as a domain to structure pedagogical choices -- Learning history : what do students know and what can they do with that knowledge? -- Teaching about Indian removal : describing and unpacking the investigative approach -- Assessing student learning -- Theorizing investigative history teaching -- How are history teachers to learn to teach using an investigative approach?.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>History</subfield>
<subfield code='x'>Study and teaching (Secondary)</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='651' ind1=' ' ind2='0'>
<subfield code='a'>United States</subfield>
<subfield code='x'>History</subfield>
<subfield code='x'>Study and teaching (Secondary)</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)475450373</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)667873193</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>E175.8 .V35 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215366506</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='p'>$36.95</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>9/21/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01392cam a2200349 a 4500</leader>
<controlfield tag='001'>a8700497</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100329s2011    maua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010012088</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780205747771 (pbk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0205747779 (pbk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>BTCTA</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>C#P</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='4'>
<subfield code='a'>LB1033</subfield>
<subfield code='b'>.C64 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Simonds, Cheri.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Communication for the classroom teacher /</subfield>
<subfield code='c'>Cheri J. Simonds, Pamela J. Cooper.</subfield>
</datafield>
<datafield tag='250' ind1=' ' ind2=' '>
<subfield code='a'>9th ed.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>Boston :</subfield>
<subfield code='b'>Allyn &amp; Bacon,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xiv, 268 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>24 cm.</subfield>
</datafield>
<datafield tag='500' ind1=' ' ind2=' '>
<subfield code='a'>Prev. eds. cataloged as: Communication for the classroom teacher / Pamela J. Cooper, Cheri J. Simonds.</subfield>
</datafield>
<datafield tag='500' ind1=' ' ind2=' '>
<subfield code='a'>Prev. ed. cataloged under Cooper, Pamela J.</subfield>
</datafield>
<datafield tag='500' ind1=' ' ind2=' '>
<subfield code='a'>Previous ed.: 2007.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 228-259) and index.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Teacher-student relationships.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Interaction analysis in education.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Oral communication.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Communication in education.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>Cooper, Pamela J.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>Cooper, Pamela J.</subfield>
<subfield code='t'>Communication for the classroom teacher.</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)587239778</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)667622659</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LB1033 .S55 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215371332</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='p'>$98.40</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>9/21/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. i:hbr  10/21/2010</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>00941pam a2200277 a 4500</leader>
<controlfield tag='001'>a8715403</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100422s2011    maua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010017390</subfield>
</datafield>
<datafield tag='015' ind1=' ' ind2=' '>
<subfield code='a'>GBB069719</subfield>
<subfield code='2'>bnb</subfield>
</datafield>
<datafield tag='016' ind1='7' ind2=' '>
<subfield code='a'>015571717</subfield>
<subfield code='2'>Uk</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780137028733 (pbk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0137028733 (pbk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>UKM</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='043' ind1=' ' ind2=' '>
<subfield code='a'>n-us---</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>LC196.5.U6</subfield>
<subfield code='b'>W54 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Wink, Joan.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Critical pedagogy :</subfield>
<subfield code='b'>notes from the real world /</subfield>
<subfield code='c'>Joan Wink.</subfield>
</datafield>
<datafield tag='250' ind1=' ' ind2=' '>
<subfield code='a'>4th ed.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>Boston :</subfield>
<subfield code='b'>Pearson,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xiii, 224 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>23 cm.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 212-220) and index.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Critical pedagogy</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC)609872217</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LC196.5 .U6 W54 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215385381</subfield>
<subfield code='k'>INPROCESS</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='p'>$47.00</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>10/13/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01204cam a2200313 a 4500</leader>
<controlfield tag='001'>a8668871</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100122s2011    nyua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010002842</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780415876483 (hbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0415876486 (hbk. : alk. paper)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780203849262 (ebk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0203849264 (ebk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>BTCTA</subfield>
<subfield code='d'>YDXCP</subfield>
<subfield code='d'>C#P</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='4'>
<subfield code='a'>LC1095</subfield>
<subfield code='b'>.C76 2011</subfield>
</datafield>
<datafield tag='245' ind1='0' ind2='0'>
<subfield code='a'>Cross-border partnerships in higher education :</subfield>
<subfield code='b'>strategies and issues /</subfield>
<subfield code='c'>edited by Robin Sakamoto and David W. Chapman.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>New York :</subfield>
<subfield code='b'>Routledge,</subfield>
<subfield code='c'>2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xii, 285 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>24 cm.</subfield>
</datafield>
<datafield tag='490' ind1='1' ind2=' '>
<subfield code='a'>International studies in higher education</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references and index.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Transnational education.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Education and globalization.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>Sakamoto, Robin.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>Chapman, David W.,</subfield>
<subfield code='d'>1947-</subfield>
</datafield>
<datafield tag='830' ind1=' ' ind2='0'>
<subfield code='a'>International studies in higher education.</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)466361104</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)666783818</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LC1095 .C76 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215361416</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='p'>$160.00</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>9/14/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01279pam a2200325 a 4500</leader>
<controlfield tag='001'>a8715402</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100409s2011    nyua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010015283</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9780132458221 (paperback)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>0132458225 (paperback)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='043' ind1=' ' ind2=' '>
<subfield code='a'>n-us---</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>LB1576</subfield>
<subfield code='b'>.W493 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Wintergerst, Ann C.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Culture :</subfield>
<subfield code='b'>practical approaches to intercultural communication /</subfield>
<subfield code='c'>Ann C. Wintergerst, Joe McVeigh ; series editor, H. Douglas Brown.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>White Plains, NY :</subfield>
<subfield code='b'>Pearson Longman,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xii, 244 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>24 cm.</subfield>
</datafield>
<datafield tag='490' ind1='1' ind2=' '>
<subfield code='a'>Tips for teaching</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 234-239) and indexes.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>English language</subfield>
<subfield code='x'>Study and teaching</subfield>
<subfield code='x'>Foreign speakers.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>English language</subfield>
<subfield code='x'>Social aspects</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Language arts</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Multicultural education</subfield>
<subfield code='z'>United States.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Children</subfield>
<subfield code='x'>Language.</subfield>
</datafield>
<datafield tag='700' ind1='1' ind2=' '>
<subfield code='a'>McVeigh, Joe.</subfield>
</datafield>
<datafield tag='830' ind1=' ' ind2='0'>
<subfield code='a'>Tips for teaching series.</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC)608296804</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>LB1576 .W493 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215383170</subfield>
<subfield code='k'>INPROCESS</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='p'>$49.33</subfield>
<subfield code='r'>Y</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>10/13/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>
<record xmlns='http://www.loc.gov/MARC21/slim'>
<leader>01367cam a2200277 a 4500</leader>
<controlfield tag='001'>a8691458</controlfield>
<controlfield tag='003'>SIRSI</controlfield>
<controlfield tag='008'>100408s2011    vaua     b    001 0 eng  </controlfield>
<datafield tag='010' ind1=' ' ind2=' '>
<subfield code='a'>  2010015303</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>9781556202940 (pbk.)</subfield>
</datafield>
<datafield tag='020' ind1=' ' ind2=' '>
<subfield code='a'>1556202946 (pbk.)</subfield>
</datafield>
<datafield tag='040' ind1=' ' ind2=' '>
<subfield code='a'>DLC</subfield>
<subfield code='c'>DLC</subfield>
<subfield code='d'>CDX</subfield>
</datafield>
<datafield tag='050' ind1='0' ind2='0'>
<subfield code='a'>HV6773</subfield>
<subfield code='b'>.B38 2011</subfield>
</datafield>
<datafield tag='100' ind1='1' ind2=' '>
<subfield code='a'>Bauman, Sheri.</subfield>
</datafield>
<datafield tag='245' ind1='1' ind2='0'>
<subfield code='a'>Cyberbullying :</subfield>
<subfield code='b'>what counselors need to know /</subfield>
<subfield code='c'>Sheri Bauman.</subfield>
</datafield>
<datafield tag='260' ind1=' ' ind2=' '>
<subfield code='a'>Alexandria, VA :</subfield>
<subfield code='b'>American Counseling Association,</subfield>
<subfield code='c'>c2011.</subfield>
</datafield>
<datafield tag='300' ind1=' ' ind2=' '>
<subfield code='a'>xiii, 204 p. :</subfield>
<subfield code='b'>ill. ;</subfield>
<subfield code='c'>26 cm.</subfield>
</datafield>
<datafield tag='504' ind1=' ' ind2=' '>
<subfield code='a'>Includes bibliographical references (p. 173-192) and index.</subfield>
</datafield>
<datafield tag='505' ind1='0' ind2=' '>
<subfield code='a'>Introduction -- Conventional bullying versus cyberbullying -- Cyberenvironments -- Types of cyberbullying -- Theories of aggressive behavior -- Developmental factors in cyberbullying -- Strategies to prevent and reduce cyberbullying -- Responding to cyberbullying -- Counseling strategies to combat cyberbullying -- Adult cyberbullying -- The role of counselors -- Additional resources.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Cyberbullying.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Cyberbullying</subfield>
<subfield code='v'>Case studies.</subfield>
</datafield>
<datafield tag='650' ind1=' ' ind2='0'>
<subfield code='a'>Bullying.</subfield>
</datafield>
<datafield tag='596' ind1=' ' ind2=' '>
<subfield code='a'>11</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-M)606405883</subfield>
</datafield>
<datafield tag='035' ind1=' ' ind2=' '>
<subfield code='a'>(OCoLC-I)667873148</subfield>
</datafield>
<datafield tag='999' ind1=' ' ind2=' '>
<subfield code='a'>HV6773 .B38 2011</subfield>
<subfield code='w'>LC</subfield>
<subfield code='c'>1</subfield>
<subfield code='i'>36105215367264</subfield>
<subfield code='d'>10/5/2010</subfield>
<subfield code='e'>10/5/2010</subfield>
<subfield code='k'>CHECKEDOUT</subfield>
<subfield code='l'>STACKS</subfield>
<subfield code='m'>EDUCATION</subfield>
<subfield code='n'>1</subfield>
<subfield code='p'>$29.95</subfield>
<subfield code='r'>M</subfield>
<subfield code='s'>Y</subfield>
<subfield code='t'>STKS-MONO</subfield>
<subfield code='u'>9/21/2010</subfield>
<subfield code='z'>TAX=8.25</subfield>
<subfield code='o'>.TECHSTAFF. EDI receipt</subfield>
</datafield>
</record>