<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>SearchWorks (SULAIR) Search Results</title>
    <link>http://searchworks.stanford.edu/view.rss?&amp;amp;f%5Baccess_facet%5D%5B%5D=At+the+Library&amp;amp;f%5Bbuilding_facet%5D%5B%5D=Cubberley+%28Education%29&amp;amp;f%5Bformat%5D%5B%5D=Book&amp;amp;per_page=10&amp;amp;sort=pub_date_sort+desc%2C+title_sort+asc</link>
    <description>SearchWorks (SULAIR) Search Results</description>
    <language>en-us</language>
    <item>
      <title>50 instructional routines to develop content literacy</title>
      <link>http://searchworks.stanford.edu/view/8548497</link>
    </item>
    <item>
      <title>Becoming biliterate</title>
      <link>http://searchworks.stanford.edu/view/8707413</link>
      <author>Kabuto, Bobbie</author>
    </item>
    <item>
      <title>Beyond survival</title>
      <link>http://searchworks.stanford.edu/view/8519432</link>
      <author>Rubinstein, Gary</author>
    </item>
    <item>
      <title>Case studies for educational leadership</title>
      <link>http://searchworks.stanford.edu/view/8513900</link>
      <author>Midlock, Stephen F.</author>
    </item>
    <item>
      <title>The challenge of rethinking history education</title>
      <link>http://searchworks.stanford.edu/view/8694933</link>
      <author>VanSledright, Bruce</author>
    </item>
    <item>
      <title>Communication for the classroom teacher</title>
      <link>http://searchworks.stanford.edu/view/8700497</link>
      <author>Simonds, Cheri</author>
    </item>
    <item>
      <title>Critical pedagogy</title>
      <link>http://searchworks.stanford.edu/view/8715403</link>
      <author>Wink, Joan</author>
    </item>
    <item>
      <title>Cross-border partnerships in higher education</title>
      <link>http://searchworks.stanford.edu/view/8668871</link>
    </item>
    <item>
      <title>Culture</title>
      <link>http://searchworks.stanford.edu/view/8715402</link>
      <author>Wintergerst, Ann C.</author>
    </item>
    <item>
      <title>Cyberbullying</title>
      <link>http://searchworks.stanford.edu/view/8691458</link>
      <author>Bauman, Sheri</author>
    </item>
  </channel>

</rss>